// Resolve WPF vs WinForms namespace conflicts (UseWindowsForms=true for NotifyIcon)
global using Application = System.Windows.Application;
global using Clipboard = System.Windows.Clipboard;
global using MessageBox = System.Windows.MessageBox;
global using MessageBoxButton = System.Windows.MessageBoxButton;
global using MessageBoxImage = System.Windows.MessageBoxImage;
global using KeyEventArgs = System.Windows.Input.KeyEventArgs;
global using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
global using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
global using Brush = System.Windows.Media.Brush;
